spring.application.name=usermicroservice

# Database configuration
spring.datasource.url=jdbc:mysql://db1:3306/mydatabase
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Add this line
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#OAuth2 Configuration
baseUrl=http://localhost:8080/api

spring.security.oauth2.client.registration.google.client-id=892123056139-nnu3elm6rmq8fsu0eubj3h0b2n1um21m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile


spring.security.oauth2.client.registration.facebook.client-id=881167911648471
spring.security.oauth2.client.registration.facebook.client-secret=87c4f1f62a4c8d97f617c31132e533ae
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/facebook
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
